sudo: required

services:
  - mysql
  - postgresql
language: python
python:
  - 3.5.0
env:
  - DJANGO=1.8.5
#install: // Install section is empty ATM, waiting for requirement analysis and tests
before_script:
  - psql -c 'CREATE DATABASE Vigilate;' -U postgres
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('toor') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'create database Vigilate;'
  - ./install-pyargon2.sh
script:
  - python manage.py test
